### ISSUE TITLE
Should explicitly declare dependency on vcredist2012

### ISSUE THREAD

**Issue by dragon788** [hansnull/chocolatey-p4merge-package#1]
This is a very small package so even if Chocolatey has to download it and simply register the fact that it is already installed, it avoids the user trying this package and going to another solution because it crashes without the msvcr110.dll available.

**Comment by hansnull** [comment]
I will add the dependency, but I am not sure if it works. In my test environment I have to force a reinstallation of the vcredist2012 package, otherwise it just does not work.
